server:
  port: 8881
spring:
  application:
    name: vehicles
    config:
    import:
      configserver: http://localhost:8761/eureka
  jpa:
    properties:
      hibernate:
        ddl-auto: none
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://construction-app-8728.7tc.aws-eu-central-1.cockroachlabs.cloud:26257/construction?sslmode=require&password=-J5_BzsUkoJWJprUrzrSGA&user=noura
    username: noura
    password: -J5_BzsUkoJWJprUrzrSGA
